version: '3.8'

services:
  db:
    image: postgres:16-alpine
    hostname: db
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - joao1barbosa-bun
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d rinha"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    hostname: redis
    networks:
      - joao1barbosa-bun

  api:
    build:
      context: ./_api
      dockerfile: Dockerfile
    hostname: api
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgres://admin:123@db:5432/rinha
      REDIS_HOST: redis
      REDIS_PORT: 6379
      API_PORT: 3000
    networks:
      - joao1barbosa-bun
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rinha.rule=PathPrefix(`/`)"
      - "traefik.http.routers.rinha.entrypoints=api"
      - "traefik.http.services.rinha.loadbalancer.server.port=3000"

  worker:
    build:
      context: ./_worker
      dockerfile: Dockerfile
    hostname: worker
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgres://admin:123@db:5432/rinha
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks:
      - joao1barbosa-bun

  traefik:
    image: traefik:v2.10
    hostname: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.api.address=:9999"
      - --log.level=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - joao1barbosa-bun

networks:
  joao1barbosa-bun:
    driver: bridge

volumes:
  pgdata: